grafana:
  adminPassword: "admin12345"
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafana.158.160.203.226.nip.io
    path: /
    pathType: Prefix
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 300m
      memory: 512Mi
  persistence:
    enabled: false

prometheus:
  ingress:
    enabled: false
  prometheusSpec:
    retention: 7d
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi
    storageSpec: {}

alertmanager:
  ingress:
    enabled: false
  alertmanagerSpec:
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi

kube-state-metrics:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

prometheus-node-exporter:
  resources:
    requests:
      cpu: 30m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 64Mi

prometheusOperator:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi
